### ISSUE TITLE
Easy to install library?

### ISSUE THREAD

**Issue by tronicgr** [tmseth/waveshare-epd-library#2]
I tried to download the library from Github and use the arduino interface to install using the zip file but it was saying that is not valid library....

So I moved the source files where there where supposed to be but on compilation I get his error...

**C:\Users\xxxxxxx\Documents\Arduino\libraries\WEPDL\wepdl.cpp:14:28: fatal error: user_interface.h: No such file or directory

compilation terminated.**

Is there any other way to download the library except GIT commands? I don't really want to use GIT on this computer and clone the library...

Thanks
Thanos

**Comment by 8tm** [comment]
After you download zip folder you need to extract and change folder name - remove branch name (-master) which it added by github.
